### ISSUE TITLE
SwiftGen의 Key와 SubKey

### ISSUE THREAD

**Issue by yyeonjju** [yyeonjju/Interview_Questions#16]
일단 SwiftGen에서 만들어주는 configuration 파일인 swiftgen.yml 파일은 크게 Key와 Subkey로 구성된다.

> yml 파일이 무엇인가?
이렇게 추가한 이 파일은 .yml 확장자인 파일입니다. 구문에 YAML을 사용하는 파일을 말하는데, 연속적인 데이터를 읽기 쉽게 도와주는 파일이라고 생각하면 됩니다. (like JSON)

https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/ConfigFile.md 참고

<br/><br/>

예시 코드
``` yml
input_dir: Sources/Resources
output_dir: Sources/Generated/
strings:
  inputs: Base.lproj
  filter: .+\.strings$
  outputs:
    - templateName: structured-swift5
      output: L10n-Constants.swift
xcassets:
  - inputs: Logos.xcassets
    outputs:
      - templateName: swift5
        output: Logos-Constants.swift
        params:
          enumName: Logos
  - inputs:
      - Colors.xcassets
      - Images.xcassets
    outputs:
      - templatePath: Resources/my-assets-custom-template.stencil
        output: Assets-Constants.swift
```

<br/><br/><br/><br/>

( 예시 코드 기준으로 설명)

# Key 

## `input_dir`
- 나머지 구성 파일에 사용되는 모든  input 앞에 이 디렉토리가 추가된다
- `inputs : - Color.xcassets`  이라고 configure file(swiftgen.yml 파일)에 작성했다면 input인 파일의 경로를 찾기위해 `input_dir` 의 디렉토리를 사용한다.

<br/>

## `output_dir`
- 나머지 구성 파일에 사용되는 모든  output 앞에 이 디렉토리가 추가된다
- ex. `output : Color+Gerated.swift`  이라고 configure file(swiftgen.yml 파일)에 작성했다면 `Color+Gerated.swift` 파일이 출력되는 디렉토리가 `output_dir` 라는 것이다!

<br/><br/>

- 지정된 모든 상대 경로는 구성 위치를 기준으로 합니다.
- 모든 입력/출력 경로가 모두 공통 상위 폴더의 하위 디렉터리에 있는 경우 각 입력 키의 모든 위치에서 공통 하위 디렉터리를 반복하지 않는 데 유용

<br/>

## `strings`, `xcassets`  : ( 이 위치는 SwiftGen의 파서parser의 위치)

- xcasset형태를 파싱하기 위한 것
- asset 말고도 다양한 것을 파싱할 수 있다고 했다
- 문서에서 말하는 파서는 이런것들이 있다 - SwiftGen parser (`colors`, `coredata`, `files`, `fonts`, `ib`, `json`, `plist`, `strings`, `xcassets`, `yaml`)
- 그래서 이런것도 가능 한 것
```yml
xcassets:
...

coredata:
...

strings:
...

ib:
...


```

<br/><br/><br/>

# SubKey

## `inputs` (필수)
- 파싱되었으면 하는 파일 혹은 디렉토리 

<br/>

## `outputs` (필수)
- `templateName`  : swift5라고 쓰면됨.
- `params`  : 파일 생성 시 옵션을 줄 수 있다.
    - `enumName`  : 따로 설정하지 않으면 기본 열거형의 이름이 Asset으로 정해진다. Color 라는 열거형으로 한정짓고 싶다면 Color or Colors 라고 작성해주면된다.
- `output`  : 생성할 출력 파일의 경로 (파싱된 것을 어느 파일로 출력할 것인지)

<br/><br/>
